# Generated by Django 3.1.7 on 2021-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
