# Generated by Django 3.1.7 on 2021-04-01 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('days', models.IntegerField(max_length=3)),
                ('departure', models.DateField()),
                ('origin', models.CharField(max_length=200)),
                ('Numberoftravellers', models.IntegerField(max_length=3)),
                ('proof', models.ImageField(upload_to='pics')),
                ('abudget', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_travel', models.CharField(max_length=10)),
                ('explore_route', models.CharField(max_length=10)),
                ('Destination_tour', models.CharField(max_length=10)),
                ('type_hotel', models.CharField(max_length=10)),
                ('location_destination', models.CharField(max_length=10)),
                ('Activities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='type_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='mode_of_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='location_destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='explore_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.place')),
            ],
        ),
    ]
