# Generated by Django 3.1.7 on 2021-04-01 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('days', models.IntegerField()),
                ('departure', models.DateField()),
                ('origin', models.CharField(max_length=200)),
                ('Numberoftravellers', models.IntegerField()),
                ('proof', models.ImageField(upload_to='pics')),
                ('abudget', models.IntegerField()),
                ('mode_of_travel', models.CharField(max_length=10)),
                ('explore_route', models.CharField(max_length=10)),
                ('Destination_tour', models.CharField(max_length=10)),
                ('type_hotel', models.CharField(max_length=10)),
                ('location_destination', models.CharField(max_length=10)),
                ('Activities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='desti')),
            ],
        ),
        migrations.DeleteModel(
            name='Basic',
        ),
        migrations.DeleteModel(
            name='travel',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location_destination',
            name='location_destination',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_hotel',
            name='th',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination_tour',
            name='dt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='explore_route',
            name='er',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mode_of_travel',
            name='mot',
            field=models.CharField(max_length=100),
        ),
    ]
