# Generated by Django 3.1.7 on 2021-04-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0003_auto_20210402_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_image',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Place.place'),
            preserve_default=False,
        ),
    ]
