# Generated by Django 3.1.7 on 2021-04-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0004_destination_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_travel',
            name='Activities',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='Destination_tour',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='explore_route',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='location_destination',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='mode_of_travel',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='type_hotel',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
