# Generated by Django 3.1.7 on 2021-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0005_auto_20210406_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_travel',
            name='Activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='Destination_tour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='explore_route',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='location_destination',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='mode_of_travel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basic_travel',
            name='type_hotel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
